name: Docker

on:
  schedule:
    - cron: '44 2 * * *'
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, self-hosted]
        include:
          - platform: ubuntu-latest
            target: linux/amd64
          - platform: self-hosted
            target: linux/arm64

    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request' && matrix.platform == 'ubuntu-latest'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-${{ matrix.target }}

      - name: Create RAM disk for Docker cache (self-hosted only)
        if: ${{ matrix.platform == 'self-hosted' }}
        run: |
          mkdir -p /dev/shm/docker-build-cache

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.target }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/dev/shm/docker-build-cache
          cache-to: type=local,dest=/dev/shm/docker-build-cache,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && matrix.platform == 'ubuntu-latest' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  manifest:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master-amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master-arm64
          
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master-amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master-arm64
          
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master
